In [1]:
import pandas as pd
import math

In [2]:
sheet_lst = ['sales', 'total_store_list', 'treatment_control_pairs', 'step_1']
sheet_dic = {}

for sheet in sheet_lst:
    sheet_dic[sheet] = pd.read_csv(f'materials/3-17_ab-test-walkthrough/sales-raw-{sheet}.csv')

In [3]:
tmp_df = sheet_dic['step_1']
tmp_df = tmp_df[tmp_df['Period']=='Comp'].groupby(['Store'], as_index=False)['Sum_Gross_Sales'].mean()
tmp_df = pd.DataFrame(tmp_df)
tmp_df.columns = ['Store', 'Avg Gross Sales for Entire Comp Period']

step1_df = pd.merge(sheet_dic['sales'], tmp_df, how='left', on='Store')
del tmp_df

step1_df['Gross Sales Growth'] = step1_df.apply(lambda row: round((row['Sum_Gross_Sales']-row['Avg Gross Sales for Entire Comp Period'])/row['Avg Gross Sales for Entire Comp Period'], 3), axis=1)
#step1_df['Gross Sales Growth'] = step1_df.apply(lambda row: (row['Sum_Gross_Sales']-row['Avg Gross Sales for Entire Comp Period'])/row['Avg Gross Sales for Entire Comp Period'], axis=1)
step1_df.head(20)

,Region,Store,Week,Week_Start,Week_End,Period,Sum_Gross_Sales,Avg Gross Sales for Entire Comp Period,Gross Sales Growth
0,Midwest,store_012,49,2014/1/9,2014/1/15,Comp,1682.54,1796.796,-0.064
1,Midwest,store_012,50,2014/1/16,2014/1/22,Comp,2387.10,1796.796,0.329
2,Midwest,store_012,51,2014/1/23,2014/1/29,Comp,1847.11,1796.796,0.028
3,Midwest,store_012,52,2014/1/30,2014/2/5,Comp,1192.87,1796.796,-0.336
4,Midwest,store_012,53,2014/2/6,2014/2/12,Comp,2996.67,1796.796,0.668
5,Midwest,store_012,54,2014/2/13,2014/2/19,Comp,1800.50,1796.796,0.002
6,Midwest,store_012,55,2014/2/20,2014/2/26,Comp,1087.62,1796.796,-0.395
7,Midwest,store_012,56,2014/2/27,2014/3/5,Comp,1655.80,1796.796,-0.078
8,Midwest,store_012,57,2014/3/6,2014/3/12,Comp,2315.13,1796.796,0.288
9,Midwest,store_012,58,2014/3/13,2014/3/19,Comp,1002.62,1796.796,-0.442
10,Midwest,store_012,59,2014/3/20,2014/3/26,Test,1498.30,1796.796,-0.166
11,Midwest,store_012,60,2014/3/27,2014/4/2,Test,2280.74,1796.796,0.269
12,Midwest,store_012,61,2014/4/3,2014/4/9,Test,1639.99,1796.796,-0.087
13,Midwest,store_012,62,2014/4/10,2014/4/16,Test,2490.09,1796.796,0.386
14,Midwest,store_012,63,2014/4/17,2014/4/23,Test,1357.89,1796.796,-0.244
15,Midwest,store_012,64,2014/4/24,2014/4/30,Test,3552.47,1796.796,0.977
16,Midwest,store_012,65,2014/5/1,2014/5/7,Test,2544.45,1796.796,0.416
17,Midwest,store_012,66,2014/5/8,2014/5/14,Test,1159.21,1796.796,-0.355
18,Midwest,store_012,67,2014/5/15,2014/5/21,Test,1241.12,1796.796,-0.309
19,Midwest,store_012,68,2014/5/22,2014/5/28,Test,1978.85,1796.796,0.101

In [4]:
step1_subdf = step1_df[['Store', 'Avg Gross Sales for Entire Comp Period']].drop_duplicates()
step1_subdf

          Store  Avg Gross Sales for Entire Comp Period
0     store_012                             1796.796000
20    store_015                             1890.905000
40    store_024                             1401.447000
60    store_027                             1155.485556
77    store_029                             2013.836000
...         ...                                     ...
1670  store_788                             2915.016000
1690  store_796                             1884.956000
1710  store_798                             2291.301000
1730  store_802                             2774.967000
1750  store_808                             1803.326000

[89 rows x 2 columns]

In [5]:
tmp_df = step1_df.groupby(['Store', 'Period'], as_index=False)['Gross Sales Growth'].mean()
step2_df = tmp_df.pivot(index='Store', columns='Period')['Gross Sales Growth'].reset_index()

del tmp_df
step2_df.head(20)

Period      Store          Comp      Test
0       store_012 -5.551115e-18  0.098800
1       store_015 -1.110223e-17 -0.542900
2       store_024 -1.000000e-04  0.200100
3       store_027 -1.111111e-04 -0.211625
4       store_029  1.000000e-04 -0.187700
5       store_033 -2.000000e-04 -0.503900
6       store_150  0.000000e+00 -0.153600
7       store_251 -1.110223e-17 -0.032222
8       store_299 -1.000000e-04 -0.080800
9       store_323 -1.387779e-18 -0.115700
10      store_462 -1.000000e-04 -0.319500
11      store_466 -1.000000e-04  0.116600
12      store_478 -2.775558e-18 -0.014000
13      store_479 -4.440892e-17 -0.159900
14      store_484  1.000000e-04 -0.405300
15      store_487 -1.000000e-04 -0.115556
16      store_489  1.000000e-04 -0.213700
17      store_490  2.000000e-04 -0.265500
18      store_491 -1.000000e-04 -0.146500
19      store_509 -2.775558e-18 -0.118333

In [6]:
def pair(store, treatment_pairing, control):
    if control == 'Control':
        return f'{store} <-> {treatment_pairing}'
    else:
        return store

tmp_df = sheet_dic['treatment_control_pairs'][['Controls', 'Treatments', 'Region']]
tmp_df.columns = ['Store', 'Treatment-Pairing', 'Region']

tmp_df = pd.merge(sheet_dic['total_store_list'], tmp_df, how='left', on=['Store', 'Region'])
tmp_df['Control-Treatment Pairing'] = tmp_df.apply(lambda row: pair(row['Store'], row['Treatment-Pairing'], row['Type']), axis=1)

step3_df = tmp_df[['Store', 'Treatment-Pairing', 'Region', 'Type', 'Control-Treatment Pairing']]
#step3_df.columns = ['store_no', 'Treatment-Pairing', 'Region', 'Type', 'Control-Treatment Pairing']

del tmp_df
step3_df.head(20)

        Store Treatment-Pairing   Region       Type Control-Treatment Pairing
0   store_015               NaN  Midwest  Treatment                 store_015
1   store_024               NaN  Midwest  Treatment                 store_024
2   store_027               NaN  Midwest  Treatment                 store_027
3   store_695               NaN  Midwest  Treatment                 store_695
4   store_696               NaN  Midwest  Treatment                 store_696
5   store_707               NaN  Midwest  Treatment                 store_707
6   store_719               NaN  Midwest  Treatment                 store_719
7   store_721               NaN  Midwest  Treatment                 store_721
8   store_724               NaN  Midwest  Treatment                 store_724
9   store_727               NaN  Midwest  Treatment                 store_727
10  store_741               NaN  Midwest  Treatment                 store_741
11  store_742               NaN  Midwest  Treatment                 store_742
12  store_755               NaN  Midwest  Treatment                 store_755
13  store_767               NaN  Midwest  Treatment                 store_767
14  store_769               NaN  Midwest  Treatment                 store_769
15  store_596               NaN     West  Treatment                 store_596
16  store_601               NaN     West  Treatment                 store_601
17  store_687         store_015  Midwest    Control   store_687 <-> store_015
18  store_728         store_015  Midwest    Control   store_728 <-> store_015
19  store_597         store_024  Midwest    Control   store_597 <-> store_024

In [7]:
step4_df = pd.merge(step3_df, step2_df, how='left')
step4_df.columns = ['Store', 'Treatment-Pairing', 'Region', 'Type', 'Control-Treatment Pairing', 'Avg Growth Comparative Period', 'Avg Growth Test Period']

step4_df.to_csv('step4_df.csv')

step4_df

,Store,Treatment-Pairing,Region,Type,Control-Treatment Pairing,Avg Growth Comparative Period,Avg Growth Test Period
0,store_015,NaN,Midwest,Treatment,store_015,-1.110223e-17,-0.542900
1,store_024,NaN,Midwest,Treatment,store_024,-1.000000e-04,0.200100
2,store_027,NaN,Midwest,Treatment,store_027,-1.111111e-04,-0.211625
3,store_695,NaN,Midwest,Treatment,store_695,2.000000e-04,-0.406800
4,store_696,NaN,Midwest,Treatment,store_696,-9.367507e-18,-0.374500
...,...,...,...,...,...,...,...
78,store_636,store_769,Midwest,Control,store_636 <-> store_769,1.000000e-04,-0.262800
79,store_594,store_596,West,Control,store_594 <-> store_596,1.110223e-17,0.042200
80,store_526,store_596,West,Control,store_526 <-> store_596,1.000000e-04,-0.331100
81,store_478,store_601,West,Control,store_478 <-> store_601,-2.775558e-18,-0.014000
82,store_527,store_601,West,Control,store_527 <-> store_601,-1.000000e-04,-0.116700

In [8]:
step5_df = step4_df.copy()
step5_df['Growth_Difference'] = step5_df.apply(lambda row: row['Avg Growth Test Period'] - row['Avg Growth Comparative Period'], axis=1)
step5_df

,Store,Treatment-Pairing,Region,Type,Control-Treatment Pairing,Avg Growth Comparative Period,Avg Growth Test Period,Growth_Difference
0,store_015,NaN,Midwest,Treatment,store_015,-1.110223e-17,-0.542900,-0.542900
1,store_024,NaN,Midwest,Treatment,store_024,-1.000000e-04,0.200100,0.200200
2,store_027,NaN,Midwest,Treatment,store_027,-1.111111e-04,-0.211625,-0.211514
3,store_695,NaN,Midwest,Treatment,store_695,2.000000e-04,-0.406800,-0.407000
4,store_696,NaN,Midwest,Treatment,store_696,-9.367507e-18,-0.374500,-0.374500
...,...,...,...,...,...,...,...,...
78,store_636,store_769,Midwest,Control,store_636 <-> store_769,1.000000e-04,-0.262800,-0.262900
79,store_594,store_596,West,Control,store_594 <-> store_596,1.110223e-17,0.042200,0.042200
80,store_526,store_596,West,Control,store_526 <-> store_596,1.000000e-04,-0.331100,-0.331200
81,store_478,store_601,West,Control,store_478 <-> store_601,-2.775558e-18,-0.014000,-0.014000
82,store_527,store_601,West,Control,store_527 <-> store_601,-1.000000e-04,-0.116700,-0.116600

In [9]:
from scipy import stats

In [10]:
arr_1 = step5_df[step5_df['Type']=='Treatment']['Growth_Difference']
arr_2 = step5_df[step5_df['Type']=='Control']['Growth_Difference']
ttest_results = stats.ttest_ind(arr_1, arr_2, equal_var=False)
ttest_results

Ttest_indResult(statistic=-1.1924271050832889, pvalue=0.24692900792352512)

In [11]:
f'{round(1 - ttest_results.pvalue, 3)*100}%'

'75.3%'

In [12]:
tmp_df = sheet_dic['total_store_list']
tmp_df = tmp_df[tmp_df['Type'] == 'Treatment'][['Store']]
tmp_df.columns = ['Treatments']

tmp_df2 = step5_df[['Store', 'Treatment-Pairing', 'Region', 'Growth_Difference']]
tmp_df2.columns = ['Controls', 'Treatments', 'Region', 'Difference_GrossSales_Control']

step6_df = pd.merge(tmp_df, tmp_df2, how='left')

tmp_df.columns = ['Controls']
tmp_df3 = pd.merge(tmp_df, tmp_df2, how='left')
tmp_df3 = tmp_df3[['Controls', 'Difference_GrossSales_Control']]
tmp_df3.columns = ['Treatments', 'Difference_GrossSales_Treatment']

step6_df = pd.merge(step6_df, tmp_df3, how='left')
step6_df = step6_df[['Controls', 'Treatments', 'Region', 'Difference_GrossSales_Control', 'Difference_GrossSales_Treatment']]

In [13]:
step6_df['Lift'] = step6_df.apply(lambda row: (row['Difference_GrossSales_Treatment']-row['Difference_GrossSales_Control'])/(1+row['Difference_GrossSales_Control']), axis=1)

del tmp_df
del tmp_df2
del tmp_df3

In [14]:
tmp_df = step1_subdf.copy()
tmp_df.columns = ['Treatments', 'Avg Sales from Comp Period']
step6_df = pd.merge(step6_df, tmp_df, how='left', on='Treatments').drop_duplicates().reset_index()
step6_df['Expected Sales Impact'] = step6_df.apply(lambda row: row['Lift']*row['Avg Sales from Comp Period'], axis=1)

del tmp_df

step6_df

,index,Controls,Treatments,Region,Difference_GrossSales_Control,Difference_GrossSales_Treatment,Lift,Avg Sales from Comp Period,Expected Sales Impact
0,0,store_687,store_015,Midwest,-0.059200,-0.542900,-0.514137,1890.905000,-972.184044
1,1,store_728,store_015,Midwest,0.174100,-0.542900,-0.610681,1890.905000,-1154.738851
2,2,store_597,store_024,Midwest,-0.515400,0.200200,1.476682,1401.447000,2069.491278
3,3,store_776,store_024,Midwest,-0.130300,0.200200,0.380016,1401.447000,532.572420
4,10,store_597,store_027,Midwest,-0.515400,-0.211514,0.627086,1155.485556,724.589377
5,11,store_776,store_027,Midwest,-0.130300,-0.211514,-0.093381,1155.485556,-107.900972
6,18,store_654,store_695,Midwest,-0.351700,-0.407000,-0.085300,1903.757000,-162.390501
7,19,store_550,store_695,Midwest,-0.245300,-0.407000,-0.214257,1903.757000,-407.893874
8,20,store_776,store_696,Midwest,-0.130300,-0.374500,-0.280786,1797.294000,-504.655852
9,22,store_788,store_696,Midwest,0.109300,-0.374500,-0.436131,1797.294000,-783.855438
10,27,store_776,store_707,Midwest,-0.130300,-0.045500,0.097505,1064.224000,103.767041
11,30,store_710,store_707,Midwest,0.077900,-0.045500,-0.114482,1064.224000,-121.834346
12,34,store_703,store_719,Midwest,-0.140100,-0.163800,-0.027561,2381.429000,-65.635385
13,35,store_615,store_719,Midwest,-0.254300,-0.163800,0.121362,2381.429000,289.016125
14,36,store_733,store_721,Midwest,0.188700,-0.395500,-0.491461,2323.660000,-1141.988872
15,37,store_760,store_721,Midwest,-0.166200,-0.395500,-0.275006,2323.660000,-639.020434
16,38,store_751,store_724,Midwest,-0.173200,0.088000,0.315917,1050.332000,331.817511
17,39,store_150,store_724,Midwest,-0.153600,0.088000,0.285444,1050.332000,299.811214
18,40,store_713,store_727,Midwest,-0.222700,-0.083200,0.179467,2003.134000,359.497225
19,41,store_700,store_727,Midwest,-0.149700,-0.083200,0.078208,2003.134000,156.660486
20,42,store_776,store_741,Midwest,-0.130300,-0.447700,-0.364953,1590.269000,-580.374130
21,47,store_798,store_741,Midwest,0.257300,-0.447700,-0.560725,1590.269000,-891.704164
22,49,store_776,store_742,Midwest,-0.130300,-0.413400,-0.325515,2542.136000,-827.502244
23,54,store_705,store_742,Midwest,0.006300,-0.413400,-0.417072,2542.136000,-1060.254873
24,56,store_251,store_755,Midwest,-0.032222,0.038600,0.073180,2178.119000,159.395299
25,57,store_577,store_755,Midwest,0.093900,0.038600,-0.050553,2178.119000,-110.110596
26,58,store_029,store_767,Midwest,-0.187800,-0.283200,-0.117459,1450.457000,-170.368872
27,59,store_714,store_767,Midwest,-0.275300,-0.283200,-0.010901,1450.457000,-15.811522
28,60,store_033,store_769,Midwest,-0.503700,0.026100,1.067499,1241.438000,1325.234440
29,61,store_636,store_769,Midwest,-0.262900,0.026100,0.392077,1241.438000,486.739360
30,62,store_594,store_596,West,0.042200,-0.241200,-0.271925,1942.662000,-528.257926
31,63,store_526,store_596,West,-0.331200,-0.241200,0.134569,1942.662000,261.422817
32,64,store_478,store_601,West,-0.014000,-0.299600,-0.289655,2044.152000,-592.099200
33,65,store_527,store_601,West,-0.116600,-0.299600,-0.207154,2044.152000,-423.454625

In [15]:
avg_lift = round(step6_df['Lift'].mean(), 3)*100
f'{avg_lift}%'

'-1.6%'

In [16]:
avg_expected_sales_impact = round(step6_df['Expected Sales Impact'].mean(), 1)
avg_expected_sales_impact

-122.4